* the play
** detailed set description
   characteristic of realism, i suppose, but still worth talking about. 
*** empty parlor
    i'm especially intrigued by
    #+BEGIN_QUOTE :location 117
    The other [double doorway with portieres] opens on a dark, windowless back
    parlor, never used except as a passage from living room to dining room.
    #+END_QUOTE
    why do the tyrones have this room? why is it never used? why does o'neill
    include it?
*** bookshelf
    #+BEGIN_QUOTE :location 117
    Against the wall between the doorways is a small bookcase, with a picture
    of Shakespeare above it, containing works by Balzac, Zola, Stendhal,
    philosophical and sociological works by Schopenhauer, Nietzsche, Marx,
    Engels, Kropotkin, Max Stirner, plays by Ibsen, Shaw, Strindberg, poetry by
    Swinburne, Rossetti, Wilde, Ernest Dowson, Kipling, etc.
    #+END_QUOTE
    this is an incredibly detailed description which the audience will
    certainly never notice.
    #+BEGIN_QUOTE :location 117--128
    Farther back is a large, glassed-in bookcase with sets of Dumas, Victor
    Hugo, Charles Lever, three sets of Shakespeare, The World's Best Literature
    in fifty large volumes, Hume's History of England, Thiers' History of the
    Consulate and Empire, Smollett's History of England, Gibbon's Roman Empire
    and miscellaneous volumes of old plays, poetry, and several histories of
    Ireland. The astonishing thing about these sets is that all the volumes
    have the look of being read and reread.
    #+END_QUOTE
** tyrone
*** clothing
    #+BEGIN_QUOTE :location 154
    His clothes, assuredly,  do not costume any romantic part. He wears a
    threadbare, ready-made, grey sack suit and shineless black shoes, a
    collar-less shirt with a thick white handkerchief knotted loosely around his
    throat. There is nothing picturesquely careless about this get-up. It is
    commonplace shabby. He believes in wearing his clothes to the limit of
    usefulness, is dressed now for gardening, and doesn't give a damn how he looks.
    #+END_QUOTE
*** cheapness, substance use
    #+BEGIN_QUOTE :location 167--180
    There's nothing like the first after-breakfast cigar, if it's a good one,
    and this new lot have the right mellow flavor. They're a great bargain,
    too. I got them dead cheap. It was McGuire put me on to them.
    #+END_QUOTE
** irishness
*** shaughnessy's victory 
    #+BEGIN_QUOTE :location 318--330
    TYRONE (Admiringly before he thinks.)
    The damned old scoundrel! By God, you can't beat him!
    (He laughs---then stops abruptly and scowls.)
    The dirty blackguard! He'll get me in serious trouble yet. I hope you told
    him I'd be mad as hell---

    EDMUND
    I told him you'd be tickled to death over the great Irish victory, and so
    you are. Stop faking, Papa.
    #+END_QUOTE
*** irish blarney
    #+BEGIN_QUOTE :location 368
    MARY (half reassured.) 
    I really should have new glasses. My eyes are so bad now.

    TYRONE (with Irish blarney.)
    Your eyes are beautiful, and well you know it.
    (He giver her a kiss. Her face lights up with a charming, shy
    embarrassment. Suddenly and startlingly one sees in her face the girl she
    had once been, not a ghost of the dead, but still a living part of her.)
    #+END_QUOTE
*** irish lilt as a sign of mary's happiness, irish hair as health
    #+BEGIN_QUOTE :location 368
    MARY
    (Laughs and an Irish lilt comes into her voice.)
    Go along with both of you!
    (Then she speaks with a girlish gravity.)
    But I did truly have beautiful hair once, didn't I, James?

    TYRONE
    The most beautiful in the world!

    MARY
    It was a rare shade of reddish brown and so long it came down below my
    knees. You ought to remember it too, Jamie. It wasn't until after Edmund
    was born that I had a single grey hair. Then it began to turn white.
    (The girlishness fades from her face.)
    #+END_QUOTE
*** irish peasants think consumption is fatal
    #+BEGIN_QUOTE :location 455
    JAMIE
    (Stares at his father, ignoring his explanation.)
    I know it's an Irish peasant idea consumption is fatal. It probably is when
    you live in a hovel on a bog, but over here, with modern treatment---

    TYRONE
    Don't I know that! What are you gabbing about, anyway? And keep your dirty
    tongue off Ireland, with your sneers about peasants and bogs and hovels!
    #+END_QUOTE
*** edmund's quiet stubbornness
    this isn't directly related to ireland, but it seems to connect to the
    irish-american identity o'neill is constructing.
    #+BEGIN_QUOTE :location 480
    JAMIE
    Besides it's damned rot! I'd like to see anyone influence Edmund more than
    he wants to be. His quietness fools people into thinking they can do what
    they like with him. But he's stubborn as hell inside and what he does is
    what he wants to do, and to hell with anyone else! What I had to do with
    all the crazy stunts he's pulled in the last few years---working his way
    all over the map as a sailor and all that stuff. I thought that was a
    damned fool idea, and I told hi, so. You can't imagine me getting fun out
    of being on the beach in South America, or living in filthy dives, drinking
    rotgut, can you? No, thanks! I'll stick to Broadway, and a room with a
    bath, and bars that serve bonded Bourbon.

    TYRONE
    You and Broadway! It's made you what you are!
    (With a touch of pride.)
    Whatever Edmund's done, he's had the guts to go off on his own, where he
    couldn't come whining to me the minute he was broke.
    #+END_QUOTE
*** starting at the bottom
    To Jamie, discussing Edmund's job as a reporter for a newspaper.
    #+BEGIN_QUOTE :location 494
    TYRONE
    Yes. He's made a start. You used to talk about wanting to become a
    newspaper man but you were never willing to start at the bottom. You expected---
    #+END_QUOTE
** Mary
*** confidence as health, nervousness as illness
    #+BEGIN_QUOTE :location 507
    TYRONE
    Yes, this time you can see how strong and sure of herself she is. She's a
    different woman entirely form the other times. She has control of her
    nerves---or she had until Edmund got sick. Now you can feel her growing
    tense and frightened underneath. I wish to God we could keep the truth from
    her, but we can't if he has to be sent to a sanatorium. What makes it worse
    is her father died of consumption. She worshiped him and she's never
    forgotten. Yes, it will be hard for her. But she can do it! She has the
    will power now! We must help her, Jamie, in every way we can!

    JAMIE (moved.)
    Of course, Papa.
    (hesitantly.)
    Outside of nerves, she seems perfectly all right this morning.

    TYRONE
    (with hearty confidence now.)
    Never better. She's full of fun and mischief.
    #+END_QUOTE
*** confidence as a constant battle against nervousness
    #+BEGIN_QUOTE :location 692--705
    [Edmund] forces a laugh in which [Mary] makes herself join. Then he goes
    out on the porch and disappears down the steps. Her first reaction is one
    of relief. She appears to relax. She sinks down in one of the wicker
    armchairs at rear of table and leans her head back, closing her eyes. But
    suddenly she grows terribly tense again. Her eyes open and she strains
    forward, seized by a fit of nervous panic. She begins a desperate battle
    with herself. Her long fingers, warped and knotted by rheumatism, drum on
    the arms of the chair, driven by an insistent life of their own, without
    her consent.
    #+END_QUOTE
