* the play
** detailed set description
   characteristic of realism, i suppose, but still worth talking about. 
*** empty parlor
    i'm especially intrigued by
    #+BEGIN_QUOTE :location 117
    The other [double doorway with portieres] opens on a dark, windowless back
    parlor, never used except as a passage from living room to dining room.
    #+END_QUOTE
    why do the tyrones have this room? why is it never used? why does o'neill
    include it?
*** bookshelf
    #+BEGIN_QUOTE :location 117
    Against the wall between the doorways is a small bookcase, with a picture
    of Shakespeare above it, containing works by Balzac, Zola, Stendhal,
    philosophical and sociological works by Schopenhauer, Nietzsche, Marx,
    Engels, Kropotkin, Max Stirner, plays by Ibsen, Shaw, Strindberg, poetry by
    Swinburne, Rossetti, Wilde, Ernest Dowson, Kipling, etc.
    #+END_QUOTE
    this is an incredibly detailed description which the audience will
    certainly never notice.
    #+BEGIN_QUOTE :location 117--128
    Farther back is a large, glassed-in bookcase with sets of Dumas, Victor
    Hugo, Charles Lever, three sets of Shakespeare, The World's Best Literature
    in fifty large volumes, Hume's History of England, Thiers' History of the
    Consulate and Empire, Smollett's History of England, Gibbon's Roman Empire
    and miscellaneous volumes of old plays, poetry, and several histories of
    Ireland. The astonishing thing about these sets is that all the volumes
    have the look of being read and reread.
    #+END_QUOTE
** tyrone
*** clothing
    #+BEGIN_QUOTE :location 154
    His clothes, assuredly,  do not costume any romantic part. He wears a
    threadbare, ready-made, grey sack suit and shineless black shoes, a
    collar-less shirt with a thick white handkerchief knotted loosely around his
    throat. There is nothing picturesquely careless about this get-up. It is
    commonplace shabby. He believes in wearing his clothes to the limit of
    usefulness, is dressed now for gardening, and doesn't give a damn how he looks.
    #+END_QUOTE
*** cheapness, substance use
    #+BEGIN_QUOTE :location 167--180
    There's nothing like the first after-breakfast cigar, if it's a good one,
    and this new lot have the right mellow flavor. They're a great bargain,
    too. I got them dead cheap. It was McGuire put me on to them.
    #+END_QUOTE
*** smoking after meals
    #+BEGIN_QUOTE :location 997
    Tyrone lights a cigar and goes to the screen door, starting out. Jamie
    fills a pipe from a jar on top of the bookcase at rear. He lights it has he
    goes to look out the window at right.
    #+END_QUOTE
** comparing the children
*** edmund is the good one; jamie is jealous
    #+BEGIN_QUOTE :location 1554--1568
    MARY
    ...
    I'm afraid Jamie has been lost to us for a long time, dear.
    (Her face hardens.)
    But we mustn't allow him to drag Edmund down with him, as he'd like to
    do. He's jealous because Edmund has always been the baby---just as he used
    to be of Eugene. He'll never be content until he makes Edmund as hopeless a
    failure as he is.
    #+END_QUOTE
** irishness
*** shaughnessy's victory 
    #+BEGIN_QUOTE :location 318--330
    TYRONE (Admiringly before he thinks.)
    The damned old scoundrel! By God, you can't beat him!
    (He laughs---then stops abruptly and scowls.)
    The dirty blackguard! He'll get me in serious trouble yet. I hope you told
    him I'd be mad as hell---

    EDMUND
    I told him you'd be tickled to death over the great Irish victory, and so
    you are. Stop faking, Papa.
    #+END_QUOTE
*** irish blarney
    #+BEGIN_QUOTE :location 368
    MARY (half reassured.) 
    I really should have new glasses. My eyes are so bad now.

    TYRONE (with Irish blarney.)
    Your eyes are beautiful, and well you know it.
    (He giver her a kiss. Her face lights up with a charming, shy
    embarrassment. Suddenly and startlingly one sees in her face the girl she
    had once been, not a ghost of the dead, but still a living part of her.)
    #+END_QUOTE
*** irish lilt as a sign of mary's happiness, irish hair as health
    #+BEGIN_QUOTE :location 368
    MARY
    (Laughs and an Irish lilt comes into her voice.)
    Go along with both of you!
    (Then she speaks with a girlish gravity.)
    But I did truly have beautiful hair once, didn't I, James?

    TYRONE
    The most beautiful in the world!

    MARY
    It was a rare shade of reddish brown and so long it came down below my
    knees. You ought to remember it too, Jamie. It wasn't until after Edmund
    was born that I had a single grey hair. Then it began to turn white.
    (The girlishness fades from her face.)
    #+END_QUOTE
*** irish peasants think consumption is fatal
    #+BEGIN_QUOTE :location 455
    JAMIE
    (Stares at his father, ignoring his explanation.)
    I know it's an Irish peasant idea consumption is fatal. It probably is when
    you live in a hovel on a bog, but over here, with modern treatment---

    TYRONE
    Don't I know that! What are you gabbing about, anyway? And keep your dirty
    tongue off Ireland, with your sneers about peasants and bogs and hovels!
    #+END_QUOTE
*** edmund's quiet stubbornness
    this isn't directly related to ireland, but it seems to connect to the
    irish-american identity o'neill is constructing.
    #+BEGIN_QUOTE :location 480
    JAMIE
    Besides it's damned rot! I'd like to see anyone influence Edmund more than
    he wants to be. His quietness fools people into thinking they can do what
    they like with him. But he's stubborn as hell inside and what he does is
    what he wants to do, and to hell with anyone else! What I had to do with
    all the crazy stunts he's pulled in the last few years---working his way
    all over the map as a sailor and all that stuff. I thought that was a
    damned fool idea, and I told hi, so. You can't imagine me getting fun out
    of being on the beach in South America, or living in filthy dives, drinking
    rotgut, can you? No, thanks! I'll stick to Broadway, and a room with a
    bath, and bars that serve bonded Bourbon.

    TYRONE
    You and Broadway! It's made you what you are!
    (With a touch of pride.)
    Whatever Edmund's done, he's had the guts to go off on his own, where he
    couldn't come whining to me the minute he was broke.
    #+END_QUOTE
*** starting at the bottom
    To Jamie, discussing Edmund's job as a reporter for a newspaper.
    #+BEGIN_QUOTE :location 494
    TYRONE
    Yes. He's made a start. You used to talk about wanting to become a
    newspaper man but you were never willing to start at the bottom. You expected---
    #+END_QUOTE
*** irish features as appealing, irish person as unintelligent
    #+BEGIN_QUOTE :location 709
    The second girl, CATHLEEN, enters from the back parlor. She carries a tray
    on which is a bottle of bonded Bourbon, several whiskey glasses, and a
    pitcher of ice water. She is a buxom Irish peasant, in her early twenties,
    with a red-cheeked comely face, black hair and blue eyes---amiable,
    ignorant, clumsy, and possessed by a dense, well-meaning stupidity. She
    puts the tray on the table. Edmund pretends to be so absorbed in his book
    he does not notice her, but she ignores this.
    #+END_QUOTE
*** reference to irish alcohol problems
    #+BEGIN_QUOTE :location 721
    CATHLEEN
    (Suddenly primly virtuous.)
    I'd never suggest a man or a woman touch drink, Mister Edmund. Sure didn't
    it kill an uncle of mine in the old country.
    (Relenting.)
    Still, a drop now and then is no harm when you're in low spirits, or have a
    bad cold.
    #+END_QUOTE
*** ireland = song
    #+BEGIN_QUOTE :location 746
    JAMIE
    I made the Old Man look at his watch. I was halfway up the walk when
    Cathleen burst into song. Our wild Irish lark! She ought to be a train announcer.
    #+END_QUOTE
*** starting at the bottom, again
    #+BEGIN_QUOTE :location 844
    MARY
    (Sharply---letting her resentment toward [Jamie] come out.)
    It's you who should have more respect! Stop sneering at your father! I
    won't have it! You ought to be proud you're his son! He may have his
    faults. Who hasn't? But he's worked hard all his life. He made his way up
    from ignorance and poverty to the top of his profession! Everyone else
    admires him and you should be the last one to sneer---you, who, thanks to
    him, have never had to work hard in your life!
    #+END_QUOTE
*** implying cathleen is lazy
    #+BEGIN_QUOTE :location 855--868
    MARY
    (With a resentment that has a quality of being automatic and on the surface
    while inwardly she is indifferent.)
    Yes, it's very trying, Jamie. You don't know how trying. You don't have to
    keep house with summer servants who don't care because they know it isn't a
    permanent position. The really good servants are all with people who have
    homes and not merely summer places. And your father won't even pay the
    wages the best summer help ask. So every year I have stupid, lazy
    greenhorns to deal with.    
    #+END_QUOTE
*** catholicism
    #+BEGIN_QUOTE :location 1085--1097
    TYRONE
    Shut up, both of you! There's little choice between the philosophy you
    learned from Broadway loafers, and the one Edmund got from his
    books. They're both rotten to the core. You've both flouted the faith you
    were born and brought up in---the one true faith of the Catholic
    Church---and your denial has brought you nothing but self-destruction.
    (His two sons stare at him contemptuously. They forget their quarrel and
    are as one against him on this issue.)

    EDMUND
    That's the bunk, Papa!

    JAMIE
    We don't pretend, at any rate.
    (Caustically.)
    I don't notice you've worn any holes in the knees of your pants going to
    Mass.

    TYRONE
    It's true I'm a bad Catholic in the observance, God forgive me. But I
    believe!
    (Angrily.)
    And you're a liar! I may not go to church but every night and morning of my
    life I get on my knees and pray!

    EDMUND
    (Bitterly.)
    Did you pray for Mama?

    TYRONE
    I did. I've prayed to God these many years for her.
    
    EDMUND
    Then Nietzsche must be right.
    (He quotes from Thus Spake Zarathustra.)
    "God is dead: of His pity for man hath God died."

    TYRONE
    (Ignores this.)
    If your mother had prayed, too--- She hasn't denied her faith, but she's
    forgotten it, until now there's no strength of the spirit left in her to
    fight against her curse.
    #+END_QUOTE
*** irish bog-trotters, consumption is fatal
    #+BEGIN_QUOTE :location 1132--1144
    JAMIE
    This is Edmund's business. What I'm afraid of is, with your Irish
    bog-trotter idea that consumption is fatal, you'll figure it would be a
    waste of money to spend any more than you can help.

    ...

    TYRONE
    (His rage still smoldering.)
    I have every hope Edmund will be cured. And keep your dirty tongue off
    Ireland! You're a fine one to sneer, with the map of it on your face!

    JAMIE
    Not after I wash my face.
    (Then before his father can react to this insult to the Old Sod, he adds
    dryly, shrugging his shoulders.)
    Well, I've said all I have to say. It's up to you.
    #+END_QUOTE
*** tyrone's people were ignorant and poverty-stricken; drink as distraction and as control
    #+BEGIN_QUOTE :location 1593
    MARY
    ...
    Please don't think I blame your father, Edmund. He didn't know any
    better. He never went to school after he was ten. His people were the most
    ignorant kind of poverty-stricken Irish. I'm sure they honestly believed
    that whiskey is the healthiest medicine for a child who is sick or
    frightened.
    (Tyrone is about to burst out in angry defense of his family but Edmund
    intervenes.)

    EDMUND (Sharply.)
    Papa!
    (Changing the subject.)
    Are we going to have this drink, or aren't we?

    TYRONE
    (Controlling himself---dully.)
    You're right. I'm a fool to take notice.
    (He picks up his glass listlessly.)
    Drink hearty, lad.
    (Edmund drinks but Tyrone remains staring at the glass in his hand. Edmund
    at once realizes how much the whiskey has been watered. He frowns, glancing
    from the bottle to his mother---starts to say something but stops.)
    #+END_QUOTE
*** homesick for ireland; die in the homeland
    #+BEGIN_QUOTE :location 1684--1697
    MARY
    ...
    Your father is a strange man, Edmund. ... His father deserted his mother
    and their six children a year or so after they came to America. He told
    them he had a premonition he would die soon, and he was homesick for
    Ireland, and wanted to go back there to die. So he went and he did die.
    #+END_QUOTE
*** mary's remembered ideal father; values of different drinks
    #+BEGIN_QUOTE :location 1978
    TYRONE
    ...
    As I've told you before, you must take her memories with a grain of
    salt. Her wonderful home was ordinary enough. Her father wasn't the great,
    generous, noble Irish gentleman she makes out. He was a nice enough man,
    good company and a good talker. I liked him and he liked me. He was
    prosperous enough, too, in his wholesale grocery business, an able man. But
    he had his weakness. She condemns my drinking but she forgets his. It's
    true he never touched a drop till he was forty, but after that he made up
    for lost time. He became a steady champagne drinker, the worse kind. That
    was his grand pose, to drink only champagne. Well, it finished him quick---
    that and the consumption---
    (He stops with a guilt glance at [Edmund].)
    #+END_QUOTE
** alcohol
*** mary's father drank while sick
    #+BEGIN_QUOTE :location 957
    MARY
    ...
    (Her eyes become fixed on the whiskey glass on the table beside
    [Edmund]---sharply.)
    Why is that glass there? Did you take a drink? Oh, how can you be such a
    fool? Don't you know it's the worst thing?
    (She turns on Tyrone.)
    You're to blame, James. How could you let him? Do you want to kill him?
    Don't you remember my father? He wouldn't stop after he was stricken. He
    said doctors were fools! He thought, like you, that whiskey is a good
    tonic!
    (A look of terror comes into her eyes and she stammers.)
    But, of course, there's no comparison at all. I don't know why I---Forgive
    me for scolding you, James. One small drink won't hurt Edmund. It might be
    good for him, if it gives him an appetite.
    (She pat's Edmund's cheek playfully, the strange detachment again in her
    manner. He jerks his head away. She seems not to notice, but she moves
    instinctively away.)
    #+END_QUOTE
*** tyrone drinks to cope
    #+BEGIN_QUOTE :location 970--982
    MARY
    ...
    (Sharply.)
    Please stop starting! One would think you were accusing me---
    (Then pleadingly.)
    James! You don't understand!

    TYRONE (With dull anger.)
    I understand that I've been a God-damned fool to believe in you!
    (He walks away from her to pour himself a big drink.)

    MARY
    ...
    (Then accusingly.)
    Why are you having another drink? You never have more than one before
    lunch.
    (Bitterly.)
    I know what to expect. You will be drunk tonight. Well, it won't be the
    first time, will it---or the thousandth?
    #+END_QUOTE
*** jamie gets a sharp tongue, tyrone holds it well, it's only a problem if it's a problem
    #+BEGIN_QUOTE :location 1171--1183
    MARY
    ...
    I'm glad Jamie is going uptown. You didn't give him any money, I hope.

    TYRONE
    I did not.

    MARY
    He'd only spend it on drink and you know what a vile, poisonous tongue he
    has when he's drunk. Not that I would mind anything he said tonight, but he
    always manages to drive you into a rage, especially if you're drunk, too,
    as you will be.

    TYRONE
    (Resentfully.)
    I won't. I never get drunk.

    MARY
    (Teasing indifferently.)
    Oh, I'm sure you'll hold it well. You always have. It's hard for a stranger
    to tell, but after thirty-five years of marriage---

    TYRONE
    I've never missed a performance in my life. That's the proof!
    (Then bitterly.)
    If I did get drunk it is not you who should blame me. No man has ever had a
    better reason.

    MARY
    Reason? What reason? You always drink too much when you go to the Club,
    don't you? Particularly when you meet McGuire. He sees to that. Don't think
    I'm finding fault, dear. You must do as you please. I won't mind.
    #+END_QUOTE
*** dangerous for edmund, the only thing jamie can do
    this is ironic because the real jamie drank himself to death.
    #+BEGIN_QUOTE :location 1349
    MARY
    I suppose you'll divide that ten dollars your father gave you with
    Jamie. You always divide with each other, don't you? Like good
    sports. Well, I know what he'll do with his share. Get drunk someplace
    where he can be with the only kind of woman he understands or likes.
    (She turns to him, pleading frightenedly.)
    Edmund! Promise me you won't drink! It's so dangerous! You know Doctor
    Hardy told you---
    #+END_QUOTE
*** bribing the servants
    #+BEGIN_QUOTE :location 1413
    MARY
    (With a flash of apprehension.)
    No, don't go, Cathleen. I don't want to be alone, yet.
    ...
    Don't worry about Bridget. I'll tell her I kept you with me, and you can
    take a big drink of whiskey to her when you go. She won't mind then.

    CATHLEEN
    (Grins---at her ease again.)
    No, Ma'am. That's the one thing can make her cheerful. She loves the drop.

    MARY
    Have yourself another drink, if you wish, Cathleen.

    CATHLEEN
    I don't know if I'd better, Ma'am. I can feel what I've had already.
    (Reaching for the bottle.)
    Well, maybe one more drink won't harm.
    (She pours a drink.)
    Here's your good health, Ma'am.
    (She drinks without bothering about a chaser.)
    #+END_QUOTE
*** quiets tempers
    #+BEGIN_QUOTE :location 1516
    CATHLEEN
    (Fighting tipsy drowsiness---sentimentally.)
    He's a fine gentleman and you're a lucky woman.
    (Then, fidgeting.)
    Can I take the drink to Bridget, Ma'am? It must be near dinnertime and I
    ought to be in the kitchen helping her. If she don't get something to quiet
    her temper, she'll be after me with the cleaver.
    #+END_QUOTE
*** tyrone holds it well
    #+BEGIN_QUOTE :location 1542--1554
    Tyrone comes in through the front parlor. Edmund is behind him. Tyrone has
    had a lot to drink but beyond a slightly glazed look in his eyes and a
    trace of blur in his speech, he does not show it. Edmund has also had more
    than a few drinks without much apparent effect, except that his sunken
    cheeks are flushed and his eyes look bright and feverish.
    #+END_QUOTE
*** jamie is the bad one because of alcohol
    #+BEGIN_QUOTE :location 1580--1593
    MARY
    (As if she hadn't heard---sadly again.)
    Who would have thought Jamie would grow up to disgrace us. You remember,
    James, for years after he went to boarding school, we received such glowing
    reports. Everyone liked him. All his teachers told us what a fine brain he
    had, and how easily he learned his lessons. Even after he began to drink
    and they had to expel him, they wrote us how sorry they were, because he
    was so likable and such a brilliant student. They predicted a wonderful
    future for him if he would only learn to take life seriously.
    (She pauses---then adds with a strange, sad detachment.)
    It's such a pity. Poor Jamie! It's hard to understand---
    (Abruptly a change comes over her. Her face hardens and she stares at her
    husband with accusing hostility.)
    No, it isn't at all. You brought him up to be a boozer. Since he first
    opened his eyes, he's seen you drinking. Always a bottle on the bureau in
    the cheap hotel rooms! And if he had a nightmare when he was little, or a
    stomach-ache, your remedy was to give him a tea-spoonful of whiskey to
    quiet him.

    TYRONE (Stung.)
    So I'm to blame because that lazy hulk has made a drunken loafer of
    himself? Is that what I came home to listen to? I might have known! When
    you have the poison in you, you want to blame everyone but yourself!

    EDMUND
    ...
    (Then, resentfully.)
    Anyway it's true. You did the same thing with me. I can remember that
    teaspoonful of booze every time I woke up with a nightmare.
    #+END_QUOTE
*** never would have married you; tyrone doesn't remember
    #+BEGIN_QUOTE :location 1618
    MARY
    ...
    But I must confess, James, although I couldn't help loving you, I would
    never have married you if I'd known you drank so much. I remember the first
    night your barroom friends had to help you up to the door of our hotel
    room, and knocked and then ran away before I came to the door. We were
    still on our honeymoon, do you remember?

    TYRONE
    (With guilty vehemence.)
    I don't remember! It wasn't on our honeymoon! And I never in my life had to
    be helped to bed, or missed a performance!
    #+END_QUOTE
*** a treat
    #+BEGIN_QUOTE :location 1671
    TYRONE
    ...
    (With angry disgust.)
    I hope to God you haven't taken to drink on top of---

    EDMUND
    Shut up, Papa!
    (To his mother, without looking at her.)
    You treated Cathleen and Bridget, isn't that it, Mama?

    MARY
    (With indifferent casualness.)
    Yes, of course. They work hard for poor wages. And I'm the housekeeper, I
    have to keep them from leaving. Besides, I wanted to treat Cathleen because
    I had her drive uptown with me, and sent her to get my prescription filled.
    #+END_QUOTE
*** a real drink as opposed to water; a subject of shame
    after learning that mary has watered down the whiskey to hide that she gave it to the
    servants:
    #+BEGIN_QUOTE :location 1684
    TYRONE
    ...
    (To Edmund.)
    I'll get a fresh bottle of whiskey, lad, and we'll have a real drink.
    (He goes through the back parlor.)
    
    MARY
    (With detached amusement.)
    He'll sneak around to the outside cellar door so the servants won't see
    him. He's really ashamed of keeping his whiskey padlocked in the
    cellar.
    #+END_QUOTE
*** to cope with mary's denial
    #+BEGIN_QUOTE :location 1759
    MARY
    [Edmund] said he didn't want any dinner. He doesn't seem to have any
    appetite these days.
    (Then stubbornly.)
    But it's just a summer cold.
    (Tyrone stares at her and shakes his head helplessly and pours himself a
    big drink and drinks it.)
    #+END_QUOTE
*** stealing vs invitation
    #+BEGIN_QUOTE :LOCATION 1771
    CATHLEEN
    ...
    (Then reading the accusation in [Tyrone's] eye.)
    Don't be looking at me that way. If I've a drop taken, I didn't steal it. I
    was invited.
    #+END_QUOTE
*** scenery: as a marker for their hopelessness
    #+BEGIN_QUOTE :location 1794
    The whiskey bottle on the tray is three-quarters empty. There is a fresh
    full bottle on the table, which he has brought from the cellar so there
    will be an ample reserve at hand. He is drunk and shows it by the owlish,
    deliberate manner in which he peers at each card to make certain of its
    identity, and then plays it as if he wasn't certain of his aim. His eyes
    have a misted, oily look and his mouth is slack. But despite all the
    whiskey in him, he has not escaped, and he looks as he appeared at the
    close of the preceding act, a sad defeated old man, possessed by hopeless
    resignation.
    #+END_QUOTE
*** as wastefulness
    During a discussion about Tyrone's desire to keep the lights out to save
    money:
    #+BEGIN_QUOTE :location 1806--1818
    EDMUND (Angrily.)
    ...
    I damned near busted my knee on the hat stand.

    TYRONE
    The light from here shows in the hall. You could see your way well enough
    if you were sober.
    
    EDMUND
    If I was sober? I like that!
    #+END_QUOTE
*** causing anger
    #+BEGIN_QUOTE
    TYRONE
    ...
    Forgive me, lad. I forgot--- You shouldn't goad me into losing my temper.

    EDMUND
    (Ashamed himself now.)
    Forget it, Papa. I apologize, too. I had no right being nasty about
    nothing. I am a bit soused, I guess.
    #+END_QUOTE
*** as camaraderie, forgetfulness, and as reinforcing itself
    #+BEGIN_QUOTE :location 1856
    TYRONE (Placatingly.)
    All right, all right, I'll stop. God knows, I don't like the subject
    either. Will you join me in a drink?

    EDMUND
    Ah! Now you're talking!

    TYRONE
    (Passes the bottle to him---mechanically.)
    I'm wrong to treat you. You've had enough already.

    EDMUND
    (Pouring a big drink---a bit drunkenly.)
    Enough is not as good as a feast.
    (He hands back the bottle.)

    TYRONE
    It's too much in your condition.

    EDMUND
    Forget my condition!
    (He raises his glass.)
    Here's how.

    TYRONE
    Drink hearty.
    (They drink.)
    #+END_QUOTE
*** as forgetfulness, yet again
    #+BEGIN_QUOTE :location 1893
    EDMUND
    ...
    We are such stuff as manure is made on, so let's drink up and forget
    it. That's more my idea.

    TYRONE (Disgustedly.)
    Ach! Keep such sentiments to yourself. I shouldn't have given you that
    drink.

    EDMUND
    It did pack a wallop, all right. On you, too.
    (He grins with affectionate teasing.)
    Even if you've never missed a performance!
    (Aggressively.)
    Well, what's wrong with being drunk? It's what we're after, isn't it? Let's
    not kid each other, Papa. Not tonight. We know what we're trying to forget.
    (Hurriedly.)
    But let's not talk about it. It's no use now.

    TYRONE (Dully.)
    No. All we can do is try to be resigned---again.

    EDMUND
    Or be so drunk you can forget.
    (He recites, and recites well, with bitter, ironical passion, the Symons'
    translation of Baudelaire's prose poem.)
    "Be always drunken. Nothing else matters: that is the only question. If you
    would not feel the horrible burden of Time weighing on your shoulders and
    crushing you to the earth, be drunken continually.

    Drunken with what? With wine, with poetry, or with virtue, as you will. But
    be drunken.

    And if sometimes, on the stairs of a palace, or on the green side of a
    ditch, or in the dreary solitude of your own room, you should awaken and
    the drunkenness be half or wholly slipped away from you, ask of the wind,
    or of the wave, or of the star, or of the bird, or of the clock, or
    whatever sighs, or rocks, or sings, or speaks, ask what hour it is; and the
    wind, wave, star, bird, clock, will answer you: 'It is the hour to be
    drunken! Be drunken, if you would not be martyred slaves of Time; be
    drunken continually! With wine, with poetry, or with virtue, as you will.'"
    #+END_QUOTE
*** a good man's failing
    #+BEGIN_QUOTE :location 1954
    TYRONE
    ...
    When I've got three good sets of Shakespeare there (he nods at the large
    bookcase) you could read.

    EDMUND (Provocatively.)
    They say he was a souse, too.

    TYRONE
    They lie! I don't doubt he liked his glass---it's a good man's
    failing---but he knew how to drink so it didn't poison his brain with
    morbidness and filthy.
    #+END_QUOTE
*** forget it!
    #+BEGIN_QUOTE
    TYRONE
    ...
    (Then he starts as he hears a sound from upstairs---with dread.)
    Did you hear? She's moving around. I was hoping she'd gone to sleep.

    EDMUND
    Forget it! How about another drink?
    ...
    Well, here's how.

    TYRONE (Mechanically.)
    Drink hearty, lad.
    #+END_QUOTE
*** a bracer
    #+BEGIN_QUOTE :location 2117
    TYRONE
    ...
    ([Edmund] looks sick and weak. His father stares at him frightenedly.)
    You look weak, lad. You'd better take a bracer.

    EDMUND
    (Grabs the bottle and pours his glass brimfull---weakly.)
    Thanks.
    (He gulps down the whiskey.)

    TYRONE
    (Pours himself a big drink, which empties the bottle, and drinks it.)
    #+END_QUOTE
*** makes tyrone generous
    #+BEGIN_QUOTE :location 2117
    TYRONE
    ...
    (He goes on dully, without resentment.)
    A stinking old miser. Well, maybe you're right. Maybe I can't help being,
    although all my life since I had anything I've thrown money over the bar to
    buy drinks for everyone in the house, or loaned money to sponges I knew
    would never pay it back---
    (With a loose-mouthed sneer of self-contempt.)
    But, of course, that was in barrooms, when I was full of whiskey. I can't
    feel that way about it when I'm sober in my home.
    #+END_QUOTE
*** as an excuse for depression, and as preventing it
    #+BEGIN_QUOTE :location 2130
    TYRONE
    ...
    But it was a game of romance and adventure to you. It was play.

    EDMUND
    (Dully sarcastic.)
    Yes, particularly the time I tried to commit suicide at Jimmie the
    Priest's, and almost did.

    TYRONE
    You weren't in your right mind.. No son of mine would ever--- You were
    drunk.

    EDMUND
    I was stone cold sober. That was the trouble. I'd stopped to think too
    long.
    #+END_QUOTE
*** deliberately giving way, hiding
    #+BEGIN_QUOTE :location 2221
    EDMUND
    For Christ's sake, Papa, forget it!
    (He reaches out and pours a drink. Tyrone starts to protest, then gives it
    up. Edmund drinks. He puts down the glass. His expression changes. When he
    speaks it is as if he were deliberately giving way to drunkenness and
    seeking to hide behind a maudlin manner.)
    #+END_QUOTE
*** drunk in other ways
    While reminiscing about his time as a sailor
    #+BEGIN_QUOTE :location 2221
    EDMUND
    ...
    I became drunk with the beauty and singing rhythm of it, and for a moment I
    lost myself---actually lost my life. I was set free! I dissolved in the
    sea, became white sails and flying spray, became beauty and rhythm.
    #+END_QUOTE
*** jamie is super duper drunk
    this is the character who irl drank himself to death.
    #+BEGIN_QUOTE :location 2247
    TYRONE
    ...
    Get [Jamie] to bed, Edmund. I'll go out on the porch. He has a tongue like
    an adder when he's drunk. I'd only lose my temper.
    (He goes out the door to the side porch as the front door in the hall bangs
    shut behind Jamie. Edmund watches with amusement Jamie's wavering progress
    through the front parlor. Jamie comes in. He is very drunk and woozy on his
    legs. His eyes are glassy, his face bloated, his speech blurred, his mouth
    slack like his father's, a leer on his lips.)

    JAMIE
    (Swaying and blinking in the doorway---in a loud voice.)
    What ho! What ho!
    #+END_QUOTE
*** jamie's desire to sink
    #+BEGIN_QUOTE :location 2271
    ([Jamie] slops a big drink into a glass.)

    EDMUND
    You're stinking now. That will knock you stiff.

    JAMIE
    Wisdom from the mouth of babes. Can the wise stuff, Kid. You're still wet
    behind the ears.
    (He lowers himself into a chair, holding the drink carefully aloft.)

    EDMUND
    All right. Pass out if you want to.

    JAMIE
    Can't, that's trouble. Had enough to sink a ship, but can't sink. Well,
    here's hoping.
    (He drinks.)
    #+END_QUOTE
*** again as an excuse for depression
    #+BEGIN_QUOTE :location 2373
    JAMIE
    ...
    (He begins to sob, and the horrible part of his weeping is that it appears
    sober, not the maudlin tears of drunkenness.)
    #+END_QUOTE
*** as a truth serum, and a glorified disease
    #+BEGIN_QUOTE :location 2413--2425
    JAMIE
    ...
    Listen, Kid, you'll be going away. May not get another chance to talk. Or
    might not be drunk enough to tell you the truth. So got to tell you
    now. Something I should have told you long ago---for your own good.
    (He pauses---struggling with himself. Edmund stares, impressed and
    uneasy. Jamie blurts out.)
    Not drunken bull, but "in vino veritas" stuff. You better take it
    seriously. Want to warn you---against me. Mama and Papa are right. I've
    been rotten bad influence. And worst of it is, I did it on purpose.
    ...
    Or part of me did. A big part. That part that's been dead so long. That
    hates life. My putting you wise so you'd learn from my mistakes. Believed
    that myself at times, but it's a fake. Made my mistakes look good. Made
    getting drunk romantic. Made whores fascinating vampires instead of poor,
    stupid, diseased slobs they really are.
    #+END_QUOTE
** metatheatricality
   #+BEGIN_QUOTE :location 2284--2296
   JAMIE
   ...
   (With contemptuous hatred.)
   What a bastard to have for a father! Christ, if you put him in a book, no
   one would believe it!
   #+END_QUOTE
** confidence as a constant battle against nervousness
*** early appearance
    #+BEGIN_QUOTE :location 692--705
    [Edmund] forces a laugh in which [Mary] makes herself join. Then he goes
    out on the porch and disappears down the steps. Her first reaction is one
    of relief. She appears to relax. She sinks down in one of the wicker
    armchairs at rear of table and leans her head back, closing her eyes. But
    suddenly she grows terribly tense again. Her eyes open and she strains
    forward, seized by a fit of nervous panic. She begins a desperate battle
    with herself. Her long fingers, warped and knotted by rheumatism, drum on
    the arms of the chair, driven by an insistent life of their own, without
    her consent.
    #+END_QUOTE
*** heroin as a solution
    #+BEGIN_QUOTE :locaiton 997
    Mary is terribly nervous again, as if the strain of sitting through lunch
    with them had been too much for her. Yet at the same time, in contrast to
    this, her expression shows more of that strange aloofness which seems to
    stand apart from her nerves and the anxieties which harry them.

    She is talking as she enters---a stream of words that issues casually, in a
    routine of family conversation, from her mouth. She appears indifferent to
    the fact that their thoughts are not on what she is saying any more than
    her own are. As she talks, she comes to the left of the table and stands,
    facing front, one hand fumbling with the bosom of her dress, the other
    playing over the table top.
    #+END_QUOTE
** detailed stage direction
*** edmund reading
    #+BEGIN_QUOTE :location 709
    Edmund sits in the armchair at left of table, reading a book. Or rather he
    is trying to concentrate on it but cannot. He seems to be listening for some
    sound from upstairs. His manner is nervously apprehensive and he looks more
    sickly than in the first act.
    #+END_QUOTE
*** doped-up mary
    #+BEGIN_QUOTE :location 806--832
    Mary enters from the front parlor. At first one notices no change except
    that she appears to be less nervous, to be more as she was when we first
    saw her after breakfast, but then one becomes aware that her eyes are
    brighter, and there is a peculiar detachment in her voice and manner, as if
    she were a little withdrawn from her words and actions.

    ...

    She kisses [Edmund]. He stops coughing and gives her a quick apprehensive
    glance, but if his suspicions are aroused her tenderness makes him renounce
    them and he believes what he wants to believe for the moment. On the other
    hand, Jamie knows after one probing look at her that his suspicions are
    justified. His eyes fall to stare at the floor, his face sets in an
    expression of embittered, defensive cynicism. Mary goes on, half sitting on
    the arm of Edmund's char, her arm around him, so her face is above and
    behind his and he cannot look into her eyes.

    ...

    He pats her hand on his shoulder. Jamie gives him a strange, almost
    contemptuous glance, wondering if his brother can really mean this. Edmund
    does not notice but his mother does.
    #+END_QUOTE
*** tyrone realizes
    #+BEGIN_QUOTE :location 943
    MARY
    ...
    (With increasing excitement.)
    Oh, I'm so sick and tired of pretending this is a home! You won't help me!
    You won't put yourself out the least bit! You don't know how to act in a
    home! You don't really want one! You never have wanted one---never since
    the day we were married! You should have remained a bachelor and lived in
    second-rate hotels and entertained your friends in barrooms!
    (She adds strangely, as if she were now talking aloud to herself rather
    than to Tyrone.)
    Then nothing would ever have happened.
    (They stare at her. Tyrone knows now. He suddenly looks a tired, bitterly
    sad old man. Edmund glances at his father and sees that he knows, but he
    still cannot help trying to warn his mother.)

    EDMUND
    Mama! Stop talking. Why don't we go in to lunch.
    #+END_QUOTE
*** edmund realizes
    #+BEGIN_QUOTE :location 957
    JAMIE
    ...
    (He comes around in back of his father, not looking at his mother, and
    grabs Edmund's shoulder.)
    Come on, Kid. Let's put on the feed bag.
    (Edmund gets up, keeping his eyes averted from his mother. They pass her,
    heading for the back parlor.)
    #+END_QUOTE
*** tyrone gets used to it
    #+BEGIN_QUOTE :location 997
    Mary is the first to enter from the back parlor. Her husband follows. He is
    not with her as he was in the similar entrance after breakfast at the
    opening of Act One. He avoids touching her or looking at her. There is
    condemnation in his face, mingled now with the beginning of an old weary,
    helpless resignation.
    #+END_QUOTE
** catholicism
*** prayer as lying to god
    #+BEGIN_QUOTE :location 1530--1542
    MARY (Bitterly.)
    You're a sentimental fool. What is so wonderful about that first meeting
    between a silly romantic schoolgirl and a matinee idol? You were much
    happier before you knew he existed, in the Convent when you used to pray to
    the Blessed Virgin.
    (Longingly.)
    If only I could find the faith I lost, so I could pray again!
    (She pauses---then begins to recite the Hail Mary in a flay, empty tone.)
    "Hail, Mary, full of grace! The Lord is with Thee; blessed art Thou among
    women."
    (Sneeringly.)
    You expect the Blessed Virgin to be fooled by a lying dope fiend reciting
    words! You can't hide from her!
    #+END_QUOTE
*** as a reason not to kill onesself
    #+BEGIN_QUOTE :location 1747
    MARY
    (Vaguely.)
    I must go upstairs. I haven't taken enough.
    (She pauses---then longingly.)
    I hope, sometime, without meaning it, I will take an overdoes. I neverppp
    could do it deliberately. The Blessed Virgin would never forgive me, then.
    #+END_QUOTE
*** shakespeare was an irish catholic
    (he wasn't)
    #+BEGIN_QUOTE :location 1818--1831
    EDMUND
    (Sits down opposite his father---contemptuously.)
    Yes, facts don't mean a thing, do they? What you want to believe, that's
    the only truth!
    (Derisively.)
    Shakespeare was an Irish Catholic, for example.

    TYRONE
    (Stubbornly.)
    So he was. The proof is in his plays.
    
    EDMUND
    Well he wasn't, and there's no proof of it in his plays, except to you!
    (Jeeringly.)
    The Duke of Wellington, there was another good Irish Catholic!

    TYRONE
    I never said he was a good one. He was a renegade but a Catholic just the
    same.

    EDMUND
    Well, he wasn't. You just want to believe that no one but an Irish Catholic
    general could beat Napoleon.
    #+END_QUOTE
